# Site settings
title: Tristan Brookes' Online Resume
email: tristan@webhaus.co.uk
baseurl: "/resume/" # the subpath of your site, e.g. /blog/
url: "http://tristyb.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
